### ISSUE TITLE
Have we supported really transparent mode?

### ISSUE THREAD

**Issue by kamenomi-dev** [webviewjs/webview#10]
As title as I say, the transparent property in the webview and browser classes' options doesn't make a difference to the window background, and the document does not provide a specific description of that.
I found some useful issues from Wry Library here: https://github.com/tauri-apps/wry/issues/1013.

**Comment by twlite** [comment]
@kamenomi-dev thanks, I will take a look when I'm free.

**Comment by kamenomi-dev** [comment]
I found a `transparent` property at src/browser_window.rs. Although it is defined, it doesn't have a specific implementation.

**Comment by FliPPeDround** [comment]
This [PR](https://github.com/webviewjs/webview/pull/11) implements the transparent mode. To achieve transparency, three steps are required:

1. Set the window's transparent property to true and decorations to false.
2. Set the webview to be transparent.
3. Set the HTML to be transparent.

Here’s an example code snippet:
```js
const app = new Application();
const window = app.createBrowserWindow({
  transparent: true,
  decorations: false,
});

const webview = window.createWebview({
    html: /* html */ `
      <html>
        <body style="background-color:rgba(87,87,87,0.5);">
          <h1>Hello, transparent!</h1>
        </body>
      </html>`,
    transparent: true,
});

app.run();
```

**Comment by twlite** [comment]
https://github.com/webviewjs/webview/releases/tag/v0.1.3
