### ISSUE TITLE
Feature Request: Support for Multiple WebViews in a Single Window

### ISSUE THREAD

**Issue by FliPPeDround** [webviewjs/webview#5]
Hello,

First of all, thank you for developing this great project; it has been immensely helpful in my work. However, I've encountered some limitations, particularly when trying to create multiple WebViews within a single window.

In desktop tool development using Node.js, it's common to need multiple WebViews in the same window, such as one for a menu bar and another to display content. I noticed that creating multiple WebViews is technically possible, as [demonstrated](https://github.com/tauri-apps/wry/blob/dev/examples/gtk_multiwebview.rs) in the wry project.

It seems that the current `@webviewjs/webview` library does not support this functionality, as the `create_browser_window` method creates both a window and a WebView simultaneously. I suggest separating the creation of windows and WebViews into distinct methods, as shown below:

```ts
import { Application } from '@webviewjs/webview';

const app = new Application();
const window = app.createWindow();
const webview = window.createWebview();
const webview1 = window.createWebview();

app.run();
```
I am raising this issue to inquire whether you would consider implementing such an API to support the need for multiple WebViews in a single window. If you agree, I am willing to attempt contributing a PR, although I am a beginner in Rust and progress may be slow.

I look forward to your response and thank you again for your hard work and excellent project.

**Comment by twlite** [comment]
Thanks for the suggestion, I will look into it 🙌

**Comment by twlite** [comment]
![image](https://github.com/user-attachments/assets/44743c77-6d86-47d8-8416-06f5914aa973)

update on this, I managed to get multiple webviews to work
