### ISSUE TITLE
Hello there? Does this webview library support borderless window?

### ISSUE THREAD

**Issue by kamenomi-dev** [webviewjs/webview#6]
Dear developer,
I want to deliver a idea that letting the `broswer` class can support ```SetBorderless``` method to customize the frame of window like VSCode.
However, the library hasn't provided this method yet for now, and has provided the method of setting the borderless when it  fullscreened. Do we could be able to achieve it?
Thanks you.

**Comment by kamenomi-dev** [comment]
(Using bad english, sorry!!!

**Comment by twlite** [comment]
@kamenomi-dev you can use `decorations: false` option of `app.createBrowserWindow` method

**Comment by kamenomi-dev** [comment]
Oh, that works, thank you!
